Repository crazyss/hypervisor_last, pull requests merged in 2020-02, with the labels that each got.

#16 The paging enable worked
  buildrules/linker.rules
  configure/helloos.lds
  hypervisor/Makefile
  hypervisor/libmmu.s
  hypervisor/mmu.c
  hypervisor/start.c
  include/mmu.h
Labels: Feature

#22 Add some of document
  README.md
  buildrules/linker.rules
Labels: enhancement

#24 fix memtest and print out total free memory/page
  hypervisor/Makefile
  hypervisor/memtest.c
  hypervisor/start.c
  include/common.h
  include/mm.h
  include/mmu.h
  lib/Makefile
Labels: bug
